# Exercice

Je dois écrire un script qui demande à l'utilisateur·rice de trouver un nombre entier compris entre 1 et 6 généré aléatoirement et qui ne s'arrête qu'à la découverte du nombre.

>[!fail] Ma proposition, qui est mauvaise pour le coup.
```
#!/bin/python3

import random

nombre_mystere = random.randint(1, 6)

nombre_encode = int(input("Encodez un nombre entier entre 1 et 6"))

  
    while nombre_encode != nombre_mystere:
      print("Super, vous avez trouvé !")
      
print("C'était bien", nombre_encode,".")
```

>[!done] Solution donnée par le cours :
```
#!/bin/python3

import random

nombre_mystere = random.randint(1,6)

reponse = int(input("Encodez un nombre (1 à 6):"))

while reponse != nombre_mystere:
    print("Ce n'est pas le nombre mystère ! Réessayez !")
    reponse = int(input("Encodez un nombre (1 à 6):"))

print("Oui, le nombre mystère était", nombre_mystere)
```

>[!warning] Bon là, comprends pas mon erreur, mis à part que j'ai noté "nombre_encode" plutôt que "reponse" bah rien ne change.


# Exercice

Je dois modifier le script ↓ pour qu'il fonctionne sans utiliser ni break ni continue.

>[!note] Le script à modifier
```
#!/bin/python3

while True:
    encodage = input("Encodez votre code (x,quit):")
    if encodage == "x":
        continue
    elif encodage == "quit":
        break
    else:
        print(encodage)
print("Fin du script")
```

>[!note] Ma modification :
```
#!/bin/python3

encodage = input("Encodez votre code (x, quit):")
while encodage != "quit":
  print(encodage)
  encodage = input("Encodez votre code (x, quit):")
print("Fin du script")
```

>[!done] Solution donnée par le cours :
```
#!/bin/python3

encodage = input("Encodez votre code (x,quit):")

while encodage != "quit":

    if encodage != "x":
        print(encodage)

    encodage = input("Encodez votre code (x,quit):")
    
print("Fin du script")
```

>[!warning] Les deux résultats sont les mêmes mais ai-je bien respecté la consigne ?

